# src/services/langgraph_agent/utils/llm_helper.py

from src.services.langgraph_agent.chains.matching_entities_finder_chain import chain as matching_entities_finder_chain
from src.services.langgraph_agent.chains.matching_entities_finder_chain import EntityResponse
from src.libs.shared_utils.logger import logger

def update_search_query(cur_search_query, prev_search_query):
    return f'{prev_search_query} {cur_search_query}'

def filter_color_search_query(search_query):
    COLORS = [
                'Customs',
                'Black',
                'Black / White',
                'True White',
                'White',
                'Brown',
                'Marshmallow White',
                'Black / Gum',
                'Emerald Green',
                'Navy Blue',
                'Blackout',
                'Deep Twilight Blue',
                'White / Black',
                'Black / Grey',
                'Stormy Weather Blue',
                'Bordeaux Red',
                'Leopard Brown / Black',
                'Navy Blue / White',
                'Red',
                'Blue',
                'Grey / Olive Green',
                'Sepia Rose Pink',
                'Lilac Mist Purple',
                'Mauvewood Pink',
                'Black / True White',
                'Off White',
                'Racing Red / White',
                'Black / Green',
                'Faded Black',
                'Pine Forest Green',
                'Bay Leaf Green',
                'Checkerboard Lilac Mist Purple',
                'Walnut Brown',
                'Coal Brown',
                'Grey',
                'Brown / Black',
                'Checkerboard Stormy Weather Blue',
                'Camo Black / Green',
                'Grape Leaf Green',
                'Chipmunk Brown',
                'Checkerboard Silver Grey',
                'Banana Cream Yellow / White',
                'Glitter Raspberry Rose Pink',
                'Drizzle Grey',
                'Checkerboard Walnut Brown',
                'Olive Grey',
                'Green',
                'Frost Grey',
                'Glitter Rose Gold Pink',
                'Dawn Pink / True White',
                'Dark Green / Dark Brown',
                'Dawn Pink',
                'Black / Red',
                'Racing Red',
                'Creme Brule Beige',
                'Grey / Black',
                'Silver Grey',
                'Checkerboard Chili Pepper Red',
                'Dazzled Black',
                'Black / Blue',
                'Dark Brown',
                'Dark Green',
                'Triple Black',
                'Camo Jungle Green',
                'Demitasse Brown',
                'White / Pink',
                'Warm Grey',
                'In the Shadows Black / Port Red',
                'Navy Blue / Yellow',
                'Yellow',
                'White / Blue',
                'Glitter Leopard Pastel Pink',
                'Pewter Grey',
                'Mushroom Brown',
                'Grey Olive Green',
                'Glazed Ginger Brown',
                'Pink / Purple',
                'Rainbow Red / Yellow / Beige',
                'Burgundy Red',
                'Dazzled Lunar Rock Grey',
                'Glitter Red',
                'Prism Pink / White',
                'Red / White',
                'Black / Racing Red',
                'Checkerboard Brown',
                'Black / Pink',
                'Checkerboard Sepia Rose Pink',
                'Dazzled Turtledove White',
                'Powder Pink / True White',
                'Beige',
                'Glitter Lilac Mist Purple',
                'Grape Leaf Green / Gum',
                'Pewter Grey / White',
                'Tobacco Brown',
                'Honeysuckle Pink',
                'After Dark Brown',
                'Marbled Yellow',
                'Navy Blue / Red',
                'Stormy Weather Black',
                'White / Mint Green',
                'Classic White',
                'Dried Kelp Green',
                'Black / Marshmallow White',
                'Glitter Leopard Pastel Blue',
                'Black / Olive Green',
                'Black / Classic White',
                'Blue / Green',
                'Brown / Green',
                'Burnt Gold Yellow',
                'Citadel Blue',
                'Navy Blue / Black',
                'Denim Black',
                'Egret White',
                'Grape Leaf Green / Oatmeal Beige',
                'Warm Beige',
                'Oatmeal Beige',
                'Olive Gray',
                'Checkerboard Black / White',
                'Spa Blue',
                'Green / Black',
                'Asphalt Grey',
                'Black / Off White',
                'Incense Brown',
                'Marshmallow White / Green',
                'Black / Pewter Grey',
                'Glitter Plaid Red / Black',
                'Camo Green / Black',
                'Checkerboard Black / Off White',
                'Pink',
                'Vintage White',
                'Evening Haze Lavender Purple / Grey',
                'Grey / Blue',
                'Dark Red / Black',
                'Off White / Pink',
                'Gun Metal Grey',
                'Deep Taupe Brown',
                'Off White / Green',
                'Scarab Green / Black',
                'Bambino Honeysuckle Pink / Blue / Gum',
                'Checkerboard Grey',
                'Snorkel Blue / Grey',
                'Coffee Brown / Brick Red',
                'Neutral Beige',
                'Marshmallow White / Beige',
                'Floral Orange / Marshmallow White',
                'Checkerboard Burnt Gold Yellow',
                'Lunar Rock Grey',
                'Stormy Weather Blue / Green',
                'White / Sepia Rose Pink',
                'Mushroom Beige',
                'Crystal White',
                'Rose Pink',
                'Limelight Green',
                'Olive Grey / Pastel Pink',
                'Oatmeal Beige / Black',
                'Turtle Dove Beige',
                'Mist Blue',
                'Chili Pepper / Mauvewood Red',
                'Unicorn White / Pink',
                'Black / Lime Green',
                'Rainbow / Beige',
                'Cumin Brown',
                'Olive Green / Gum',
                'Coral Blush Pink',
                'Barbed Off White',
                'Light Grey',
                'Warm Taupe Brown / White',
                'Marshmallow White / Mushroom Beige',
                'Geo Check Frost Grey',
                'Camo Brown',
                'Brown / Grape Leaf Green',
                'Camo Black',
                'Kelp Green',
                'Port Royale Red / White',
                'Iceberg Green / White',
                'True White / Black',
                'Spikes Black',
                'Fuchsia Red',
                'Marshmallow White / Vintage Blue',
                'Blue / Black / Purple',
                'Storm Grey',
                'Checkerboard Green / White',
                'Chocolate Plum Brown',
                'Willowherb Purple / Gum',
                'Pink / White',
                'Black / White / Pink',
                'Harvest Gold Yellow',
                'Blue / Marshmallow White',
                'Blue / White',
                'Estate Blue',
                'White / Sun-Dried Tomato Red',
                'Brown / Sepia Rose Pink',
                'Khaki Brown',
                'Pink Glo',
                'Incense Tan Brown',
                'White / Red / Gum',
                'Turtledove Beige',
                'Marmalade Orange / Beige',
                'Checkerboard Navy Blue',
                'Dark Purple',
                'Rose Gold Pink',
                'Pistachio Green / White',
                'Evening Haze Lavender Purple / Beige',
                'Camo Green',
                'Geo Check Bordeaux Red',
                'White / True Blue',
                'Cheetah Navy Blue',
                'Black / Purple',
                'Banana Cream Yellow',
                'Blue / Yellow / Rainbow',
                'Solar Orange',
                'Spooky Black',
                'Burro Brown',
                'White / Olive Grey',
                'Baby Blue',
                'Black / Yellow / Orange',
                'Fluro Lime Green',
                'Atiba Black / Dark Green',
                'Checkerboard Red',
                'Grey Olive Green / White',
                'Eden Green',
                'Brown / Marshmallow White',
                'Desert Brown / Chipmunk Brown',
                'Flame Red / Orange / Yellow',
                'Natural Beige',
                'Orange / Brown',
                'Black / Blue / Green',
                'Foxglove Pink',
                'Deep Twilight Blue / Lilac Mist',
                'Grey / Beige',
                'Turtle Dove White',
                'Houndstooth Black / White',
                'Gum Black / White',
                'Khaki Brown / Burnt Orange',
                'Atiba Oatmeal Beige',
                'Black / White / Red',
                'Blanc De Blanc White',
                'White Grey',
                'Pale Petal Pink',
                'Marshmallow / True White',
                'Twilight Blue',
                'Checkerboard Mushroom Brown',
                'Lilac Purple',
                'Racing Red / Marshmallow White',
                'Dachshund Brown / Black / Rasta',
                'Marshmallow White / Emerald Green',
                'Black / Orange',
                'Heritage Blue / Gum',
                'Grunge Core Black',
                'Racing Red / Navy Blue',
                'Camo Oatmeal / Afterdark Beige',
                'Checkerboard Black',
                'Odyssey Brown',
                'Oatmeal Beige / Brown',
                'Atiba Solar Orange',
                'Checkerboard Walnut Brown / White',
                'Parisian Night Black',
                'Atiba Emerald Green',
                'Brown / Gum',
                'Black / Sepia Rose Pink',
                'Checkerboard Creme Brule Beige',
                'Mushroom Grey',
                'Desert Camo Brown',
                'Leopard Black',
                'Checkerboard Crimson Red / True White',
                'Mushroom Brown / Sepia Rose Pink',
                'Checkerboard Orange / True White',
                'Space Molly Reflective Marshmallow White / Grey',
                'Space Molly Oatmeal Beige / Sepia Rose Pink',
                'Taupe Mist Beige / Sea Green',
                'Checkerboard Yellow / Red',
                'Space Molly Black / Dachshund Brown',
                'Checkerboard Burgundy Red / Gold',
                'Denim Blue',
                'Light Denim Blue',
                'Checkerboard Red / Gold',
                'Zebra Black / True White',
                'Drizzle Grey / White',
                'Glitter Plaid Incense',
                'Dots Pink Lemonade Pink',
                'Two-Tone Denim Blue',
                'Glitter Plaid Incense Brown',
                'Space Molly Oatmeal Beige / Mist Blue',
                'Floral Black',
                'Brown / White',
                'Black / Silver Grey',
                'Barbed Black',
                'Off White / Black',
                'Charcoal Grey',
                'Checkerboard Deep Twilight Purple',
                'Black / Brown',
                'Peyote Beige / Black',
                'Croc Grape Purple',
                'Loden Green',
                'Muave / Beige / Black',
                'Orange / Black',
                'Checkerboard Marshmallow White',
                'Tan Brown',
                'Citrus Yellow',
                'Star Egret',
                'Dress Blues',
                'Purple / Pink',
                'Demitasse Brown / Green',
                'Burnt Gold Yellow / Stormy Weather Blue',
                'Black / Chili Pepper Red',
                'Tap Shoe Green',
                'Rock Salt Off White',
                'Adobe Brown',
                'Raspberry Pink / Gum',
                'Odyssey Black / Red',
                'Black / Solar Orange',
                'Elm Tan Beige',
                'Stv Navy Blue',
                'Grey Blue',
                'Pastel Blue / Green / Orange',
                'Indigo Blue',
                'Off Road Egret White',
                'Off Road Elm Green',
                'Star Black',
                'True Blue',
                'Mauvewood Pink / White',
                'Marshmallow White / True Blue',
                'Cream Beige',
                'London Fog Grey / Black / Blue',
                'Canary Yellow',
                'Glitter Cloud Blue',
                'Checkerboard Blue',
                'Dusty Olive Blue',
                'Black / Gold Yellow',
                'Cream White',
                'Brown / Red',
                'Olive Green / White',
                'Sepia Orange',
                'Washed Black',
                'Taupe Beige',
                'Checkerboard Deep Twilight Blue',
                'Powder Pink',
                'Bordeaux Red / Marshmallow White',
                'Kelp Green / Marshmallow White',
                'Deep Twilight Purple',
                'Forest Green',
                'Light Brown / Dark Brown',
                'Dark Grey',
                'Dark Blue',
                'Checkerboard Black / Blue',
                'Checkerboard Grey / Black',
                'Gothic Grape Purple',
                'Checkerboard Military Green',
                'Pink / True White',
                'Natural White',
                'Checkerboard Sepia Rose',
                'Vintage Gothic Grape Purple',
                'Marshmallow White / Metallic Pink',
                'Shadow Lime Green',
                'Black / Mustard Yellow'
            ]
    
    
    return None

def find_matched_entities(search_query: str, product_context: str):
    """Return list of entities with confidence scores using structured Pydantic output."""
    try:
        result: EntityResponse = matching_entities_finder_chain.invoke({
            "search_query": search_query,
            "product_context": product_context
        })
        return [e.model_dump() for e in result.entities]
    except Exception as e:
        logger.error("⚠️ LLM/Parsing Error:", e)
        return []